### ISSUE TITLE
 Resolution failed several times for dependency: org.apache.logging.log4j#log4j-api;2.11.1

### ISSUE THREAD

**Issue by georgeOsdDev** [xitrum-framework/xitrum-new#18]
We can't start xitrum-new scaffold project with `sbt/sbt fgRun`.
I'm not sure this issue is belong to SBT or xitrum-new
https://github.com/sbt/sbt/blob/develop/project/Dependencies.scala#L136

```
oshidatakeharu at OshidaIMac in ~/tmp
$ git clone https://github.com/xitrum-framework/xitrum-new.git
Cloning into 'xitrum-new'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1072 (delta 0), reused 3 (delta 0), pack-reused 1066
Receiving objects: 100% (1072/1072), 7.92 MiB | 5.24 MiB/s, done.
Resolving deltas: 100% (488/488), done.
Checking connectivity... done.

oshidatakeharu at OshidaIMac in ~/tmp
$ cd xitrum-new

oshidatakeharu at OshidaIMac in ~/tmp/xitrum-new (master)
$ sbt/sbt fgRun
[info] Loading settings for project xitrum-new-build from plugins.sbt ...
[info] Loading project definition from /Users/oshidatakeharu/tmp/xitrum-new/project
[info] Updating ProjectRef(uri("file:/Users/oshidatakeharu/tmp/xitrum-new/project/"), "xitrum-new-build")...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.apache.logging.log4j#log4j-api;2.11.1: Resolution failed several times for dependency: org.apache.logging.log4j#log4j-api;2.11.1 {compile=[compile(*), master(*)], runtime=[runtime(*)]}::
[warn] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j-api;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j-api/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j-api;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j-api/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	Resolution failed several times for dependency: org.apache.logging.log4j#log4j;2.11.1 {}::
[warn] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/jars/log4j.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn]
[warn] 	:: org.apache.logging.log4j#log4j-core;2.11.1: Resolution failed several times for dependency: org.apache.logging.log4j#log4j-core;2.11.1 {compile=[compile(*), master(*)], runtime=[runtime(*)]}::
[warn] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j-core;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j-core/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j-core;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j-core/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	Resolution failed several times for dependency: org.apache.logging.log4j#log4j;2.11.1 {}::
[warn] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/jars/log4j.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn]
[warn] 	:: org.apache.logging.log4j#log4j-slf4j-impl;2.11.1: Resolution failed several times for dependency: org.apache.logging.log4j#log4j-slf4j-impl;2.11.1 {compile=[compile(*), master(*)], runtime=[runtime(*)]}::
[warn] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j-slf4j-impl;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j-slf4j-impl/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j-slf4j-impl;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j-slf4j-impl/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	Resolution failed several times for dependency: org.apache.logging.log4j#log4j;2.11.1 {}::
[warn] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/jars/log4j.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn]
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.apache.logging.log4j:log4j-api:2.11.1
[warn] 		  +- org.scala-sbt:util-logging_2.12:1.2.4
[warn] 		  +- org.scala-sbt:protocol_2.12:1.2.7
[warn] 		  +- org.scala-sbt:command_2.12:1.2.7
[warn] 		  +- org.scala-sbt:main-settings_2.12:1.2.7
[warn] 		  +- org.scala-sbt:main_2.12:1.2.7
[warn] 		  +- org.scala-sbt:sbt:1.2.7
[warn] 		  +- default:xitrum-new-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn] 		org.apache.logging.log4j:log4j-core:2.11.1
[warn] 		  +- org.scala-sbt:util-logging_2.12:1.2.4
[warn] 		  +- org.scala-sbt:protocol_2.12:1.2.7
[warn] 		  +- org.scala-sbt:command_2.12:1.2.7
[warn] 		  +- org.scala-sbt:main-settings_2.12:1.2.7
[warn] 		  +- org.scala-sbt:main_2.12:1.2.7
[warn] 		  +- org.scala-sbt:sbt:1.2.7
[warn] 		  +- default:xitrum-new-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn] 		org.apache.logging.log4j:log4j-slf4j-impl:2.11.1
[warn] 		  +- org.scala-sbt:main_2.12:1.2.7
[warn] 		  +- org.scala-sbt:sbt:1.2.7
[warn] 		  +- default:xitrum-new-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.apache.logging.log4j#log4j-api;2.11.1: Resolution failed several times for dependency: org.apache.logging.log4j#log4j-api;2.11.1 {compile=[compile(*), master(*)], runtime=[runtime(*)]}::
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j-api;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j-api/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j-api;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j-api/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	Resolution failed several times for dependency: org.apache.logging.log4j#log4j;2.11.1 {}::
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/jars/log4j.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error]
[error]
[error] unresolved dependency: org.apache.logging.log4j#log4j-core;2.11.1: Resolution failed several times for dependency: org.apache.logging.log4j#log4j-core;2.11.1 {compile=[compile(*), master(*)], runtime=[runtime(*)]}::
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j-core;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j-core/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j-core;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j-core/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	Resolution failed several times for dependency: org.apache.logging.log4j#log4j;2.11.1 {}::
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/jars/log4j.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error]
[error]
[error] unresolved dependency: org.apache.logging.log4j#log4j-slf4j-impl;2.11.1: Resolution failed several times for dependency: org.apache.logging.log4j#log4j-slf4j-impl;2.11.1 {compile=[compile(*), master(*)], runtime=[runtime(*)]}::
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j-slf4j-impl;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j-slf4j-impl/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j-slf4j-impl;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j-slf4j-impl/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	Resolution failed several times for dependency: org.apache.logging.log4j#log4j;2.11.1 {}::
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/jars/log4j.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error]
[error]
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvyActions$$$Lambda$2455/813787891.apply(Unknown Source)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module$$Lambda$2456/1959230323.apply(Unknown Source)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt$$Lambda$2457/1794547268.apply(Unknown Source)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2451/1106628856.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.util.Tracked$$$Lambda$2407/1496331948.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2453/286159553.apply(Unknown Source)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2450/1805501487.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.util.Tracked$$$Lambda$2380/349245024.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2561)
[error] 	at sbt.Classpaths$$$Lambda$1574/625361236.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1$$Lambda$1463/106116649.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$2292/328708417.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.Execute$$Lambda$2309/1974711972.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.Execute$$Lambda$2300/1475453406.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2307/28783325.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: org.apache.logging.log4j#log4j-api;2.11.1: Resolution failed several times for dependency: org.apache.logging.log4j#log4j-api;2.11.1 {compile=[compile(*), master(*)], runtime=[runtime(*)]}::
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j-api;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j-api/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j-api;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j-api/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	Resolution failed several times for dependency: org.apache.logging.log4j#log4j;2.11.1 {}::
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/jars/log4j.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error]
[error]
[error] unresolved dependency: org.apache.logging.log4j#log4j-core;2.11.1: Resolution failed several times for dependency: org.apache.logging.log4j#log4j-core;2.11.1 {compile=[compile(*), master(*)], runtime=[runtime(*)]}::
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j-core;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j-core/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j-core;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j-core/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	Resolution failed several times for dependency: org.apache.logging.log4j#log4j;2.11.1 {}::
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/jars/log4j.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error]
[error]
[error] unresolved dependency: org.apache.logging.log4j#log4j-slf4j-impl;2.11.1: Resolution failed several times for dependency: org.apache.logging.log4j#log4j-slf4j-impl;2.11.1 {compile=[compile(*), master(*)], runtime=[runtime(*)]}::
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j-slf4j-impl;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j-slf4j-impl/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j-slf4j-impl;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j-slf4j-impl/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	Resolution failed several times for dependency: org.apache.logging.log4j#log4j;2.11.1 {}::
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.logging.log4j/log4j/2.11.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	typesafe-ivy-releases: unable to get resource for org.apache.logging.log4j#log4j;2.11.1: res=https://repo.typesafe.com/typesafe/ivy-releases/org.apache.logging.log4j/log4j/2.11.1/jars/log4j.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error]
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```

**Comment by ngocdaothanh** [comment]
It's because the dependency JAR files couldn't be downloaded.

There are many errors in your message:
`javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

I don't have that problem on my Mac.
I'm using Java 1.8.0_131.

Maybe you are using an old (or new) version of Java?

**Comment by georgeOsdDev** [comment]
Thanks, I updated jdk from `1.8.0_25` to `1.8.0_202` and problem is resolved.
