### ISSUE TITLE
Investigate problem with Agent7

### ISSUE THREAD

**Issue by ngocdaothanh** [xitrum-framework/xitrum-new#8]
From a Xitrum user:

```
cd xitrum-new-master/
DAO-no-MacBook-Pro:xitrum-new-master dmquan$ sbt/sbt run
Exception in thread "main" java.lang.UnsupportedClassVersionError: agent7/Agent : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:280)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:338)
FATAL ERROR in native method: processing of -javaagent failed
sbt/sbt: line 16:   536 Abort trap: 6           $java_cmd -javaagent:`dirname $0`/agent7-1.0.jar -Xms256M -Xmx512M -Xss1M -XX:+CMSClassUnloadingEnabled $memopts -jar `dirname $0`/sbt-launch-0.13.7.jar "$@"
```

May be it's because he's using JRE/JDK lower than 7:
http://stackoverflow.com/questions/10382929/unsupported-major-minor-version-51-0

**Comment by ngocdaothanh** [comment]
The problem is solved after the user upgrades his Java version.
